 version: 2
 updates:
   - package-ecosystem: "gomod"
     directory: "/"
     target-branch: "main"
     schedule:
       interval: "monthly"
       day: "friday"          # Run on the first day of the month
       time: "05:00"         # 5 AM UTC (10:45 AM NPT)
       timezone: "Asia/Kathmandu"
     assignees:
       - "mukeshmahato17"
     ignore:
       - dependency-name: "*"
         update-types: ["version-update:semver-patch"]